export { AuthSkeleton } from './auth-skeleton'
export { DashboardSkeleton } from './dashboard-skeleton'
export { HomepageSkeleton } from './homepage-skeleton'
export { MenuSkeleton } from './menu-skeleton'
export { OrderSkeleton } from './order-skeleton'
export { OrderStatusSkeleton } from './order-status-skeleton'
export { SettingsSkeleton } from './settings-skeleton'
export { LocationSkeleton } from './location-skeleton'
